services:
  backend:
    build: ./backend
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://postgres:PasswordDBWEB2025&@176.108.249.27:5432/psycho
      - UPLOAD_DIR=/app/uploads
      - DOCKER_CONTAINER=true
    volumes:
      - ./backend/uploads:/app/uploads
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "80:80"
      - "443:443"                        # ← добавить
    volumes:
      - /etc/nginx/ssl:/etc/nginx/ssl:ro # ← проброс сертификатов
    depends_on:
      - backend
    restart: unless-stopped