services:
  backend:
    build: ./backend
    ports:
      - "8001:8001"  # Изменяем внешний порт на 8001
    environment:
      - DATABASE_URL=postgresql://postgres:PasswordDBWEB2025&@176.108.249.27:5432/psycho
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build: ./frontend
    ports:
      - "80:80"  # Изменяем внешний порт фронтенда на 8080
    depends_on:
      - backend
  #     - express

  # caruselbackend:
  #   build:
  #     context: ./comics-carousel
  #     dockerfile: Dockerfile.backend
  #   container_name: comics_backend
  #   ports:
  #     - "3001:3001"
  #   environment:
  #     - PORT=3001
  #     - NODE_ENV=production
  #     - DATABASE_URL=postgresql://postgres:PasswordDBWEB2025&@176.108.249.27:5432/database_comics
  #   restart: unless-stopped

  # caruselfrontend:
  #   build:
  #     context: ./comics-carousel
  #     dockerfile: Dockerfile.frontend
  #   container_name: comics_frontend
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - caruselbackend
  #   restart: unless-stopped