services:
  carouselbackend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: comics_backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:PasswordDBWEB2025&@176.108.249.27:5432/database_comics
    restart: unless-stopped

  carouselfrontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: comics_frontend
    ports:
      - "80:80"
    depends_on:
      - carouselbackend
    restart: unless-stopped