FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Создаем правильную структуру папок
RUN mkdir -p /app/public && \
    ln -sf /app/server/public/images /app/public/images && \
    chmod -R 755 /app/public && \
    chmod -R 755 /app/server/public

EXPOSE 5088

CMD ["node", "/app/server.js"]