services:
  carouselfrontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: comics_frontend
    ports:
      - "5088:80"
    depends_on:
      - carouselbackend
    restart: unless-stopped

  carouselbackend:
    build: ./server
    ports:
      - "5088:3001"  # Изменяем внешний порт на 3001
    volumes:
      - ./server/public/images:/app/public/images
