# Dockerfile.frontend
FROM node:18-alpine AS build

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Production stage - Nginx
FROM nginx:stable-alpine

# Копируем собранный React в Nginx
COPY --from=build /app/build /usr/share/nginx/html

# Копируем конфиг Nginx (создадим ниже)
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]