# frontend/Dockerfile
FROM node:18-alpine as build

WORKDIR /app

# Копируем ТОЛЬКО файлы фронтенда
COPY package.json package-lock.json ./
RUN npm install

# Копируем исходники фронтенда (src, public)
COPY public ./public
COPY src ./src
COPY .env* ./

RUN npm run build

# Production stage
FROM nginx:alpine

# Копируем собранный фронт
COPY --from=build /app/build /usr/share/nginx/html

# Копируем конфиг Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]